apiVersion: v1
kind: Secret
metadata:
  name: kserve-minio-secret
  annotations:
     serving.kserve.io/s3-endpoint: 'storage-api.course.aiengineer.codex-platform.com' 
     serving.kserve.io/s3-usehttps: "1" 
     serving.kserve.io/s3-region: 'eu-west-1'
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: minio-kserve
  AWS_SECRET_ACCESS_KEY: minio-kserve
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-minio-sa
secrets:
- name: kserve-minio-secret
